import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import MainProvider from "@/providers/MainProvider";



export const metadata: Metadata = {
  title: "Notes manages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
